# Generated by Django 3.2 on 2021-09-30 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted_tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, max_length=40, null=True)),
                ('material_id', models.CharField(blank=True, max_length=40, null=True)),
                ('quantity', models.CharField(blank=True, max_length=40, null=True)),
                ('size', models.CharField(blank=True, max_length=40, null=True)),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
                ('weight', models.CharField(blank=True, max_length=40, null=True)),
                ('date', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='essentialitemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=400, null=True)),
                ('ES_Date', models.DateField(blank=True, null=True)),
                ('ES_Size', models.CharField(blank=True, max_length=400, null=True)),
                ('ES_Quantity', models.CharField(blank=True, max_length=400, null=True)),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FMstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FM_Date', models.DateField(blank=True, null=True)),
                ('Size', models.CharField(blank=True, max_length=40, null=True)),
                ('Grade', models.CharField(blank=True, max_length=40, null=True)),
                ('coilWeight', models.CharField(blank=True, max_length=40, null=True)),
                ('materialType', models.CharField(blank=True, max_length=40, null=True)),
                ('FM_Thickness', models.CharField(blank=True, max_length=40, null=True)),
                ('FM_Size', models.CharField(blank=True, max_length=40, null=True)),
                ('FM_Weight', models.CharField(blank=True, max_length=40, null=True)),
                ('FM_Quantity', models.CharField(blank=True, max_length=40, null=True)),
                ('FM_scrapWeight', models.CharField(blank=True, max_length=40, null=True)),
                ('UF_Thickness', models.CharField(blank=True, max_length=40, null=True)),
                ('UF_Size', models.CharField(blank=True, max_length=40, null=True)),
                ('UF_Weight', models.CharField(blank=True, max_length=40, null=True)),
                ('UF_Quantity', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.CharField(blank=True, max_length=40, null=True)),
                ('Username', models.CharField(blank=True, max_length=40, null=True)),
                ('CRUDoperation', models.CharField(blank=True, max_length=40, null=True)),
                ('Table_name', models.CharField(blank=True, max_length=40, null=True)),
                ('Table_id', models.CharField(blank=True, max_length=40, null=True)),
                ('Log_Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=400, null=True)),
                ('text', models.CharField(blank=True, max_length=400, null=True)),
                ('date', models.CharField(blank=True, max_length=400, null=True)),
                ('stock_count', models.CharField(blank=True, max_length=400, null=True)),
                ('seen', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_Type', models.CharField(blank=True, max_length=40, null=True)),
                ('t_id', models.CharField(blank=True, max_length=40, null=True)),
                ('s_weight', models.CharField(blank=True, max_length=40, null=True)),
                ('S_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_time', models.CharField(blank=True, max_length=40, null=True)),
                ('inactive_time', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UFMstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UFM_type', models.CharField(blank=True, max_length=40, null=True)),
                ('UFM_date', models.DateField(blank=True, null=True)),
                ('UFM_Weight', models.CharField(blank=True, max_length=40, null=True)),
                ('UFM_Quantity', models.CharField(blank=True, max_length=40, null=True)),
                ('FMid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apex.fmstock')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sale_Type', models.CharField(blank=True, max_length=40, null=True)),
                ('Sale_date', models.DateField(blank=True, null=True)),
                ('Sale_Weight', models.CharField(blank=True, max_length=40, null=True)),
                ('Sale_Quantity', models.CharField(blank=True, max_length=40, null=True)),
                ('Stock', models.CharField(blank=True, max_length=40, null=True)),
                ('To', models.CharField(blank=True, max_length=40, null=True)),
                ('FMcoilUID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apex.fmstock')),
                ('UFcoilID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apex.ufmstock')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=40, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=40, null=True)),
                ('UserName', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
                ('userRole', models.CharField(blank=True, max_length=40, null=True)),
                ('delete_access', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='rawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor', models.CharField(blank=True, max_length=40, null=True)),
                ('RM_Date', models.DateField(blank=True, null=True)),
                ('RM_Thickness', models.CharField(blank=True, max_length=40, null=True)),
                ('RM_Size', models.CharField(blank=True, max_length=40, null=True)),
                ('RM_Grade', models.CharField(blank=True, max_length=40, null=True)),
                ('RM_coilWeight', models.CharField(blank=True, max_length=40, null=True)),
                ('RM_currentCoilWeight', models.CharField(blank=True, max_length=40, null=True)),
                ('RM_scrapWeight', models.CharField(blank=True, max_length=40, null=True)),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fmstock',
            name='coilUID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apex.rawmaterial'),
        ),
        migrations.AddField(
            model_name='fmstock',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EssentialItemUsePerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EPD_Type', models.CharField(blank=True, max_length=40, null=True)),
                ('EPD_Size', models.CharField(blank=True, max_length=40, null=True)),
                ('EPD_Date', models.DateField(blank=True, null=True)),
                ('EPD_Quantity', models.CharField(blank=True, max_length=40, null=True)),
                ('EPD_UID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apex.essentialitemstock')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
